# Generated by Django 5.1.4 on 2025-01-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название породы')),
                ('size', models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20, verbose_name='Размер породы')),
                ('friendliness', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Дружелюбие породы')),
                ('trainability', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Обучаемость породы')),
                ('shedding_amount', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Количество линьки шерсти')),
                ('exercise_needs', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Необходимые упражнения')),
            ],
            options={
                'verbose_name': 'порода',
                'verbose_name_plural': 'породы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя собаки')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст собаки')),
                ('gender', models.CharField(max_length=20, verbose_name='Пол собаки')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет собаки')),
                ('favorite_food', models.CharField(max_length=100, verbose_name='Любимая еда собаки')),
                ('favorite_toy', models.CharField(max_length=100, verbose_name='Любимая игрушка собаки')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.breed', verbose_name='Порода собаки')),
            ],
            options={
                'verbose_name': 'собака',
                'verbose_name_plural': 'собаки',
                'ordering': ('name',),
            },
        ),
    ]
